// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsservices.proxies;

public class CognitoCredentials
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cognitoCredentialsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSServices.CognitoCredentials";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccessKey("AccessKey"),
		SecretKey("SecretKey"),
		Username("Username"),
		Password("Password"),
		IdentityPoolId("IdentityPoolId"),
		Credentials_CognitoCredentials("AWSServices.Credentials_CognitoCredentials");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CognitoCredentials(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AWSServices.CognitoCredentials"));
	}

	protected CognitoCredentials(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cognitoCredentialsMendixObject)
	{
		if (cognitoCredentialsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AWSServices.CognitoCredentials", cognitoCredentialsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AWSServices.CognitoCredentials");

		this.cognitoCredentialsMendixObject = cognitoCredentialsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CognitoCredentials.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static awsservices.proxies.CognitoCredentials initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return awsservices.proxies.CognitoCredentials.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static awsservices.proxies.CognitoCredentials initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsservices.proxies.CognitoCredentials(context, mendixObject);
	}

	public static awsservices.proxies.CognitoCredentials load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsservices.proxies.CognitoCredentials.initialize(context, mendixObject);
	}

	public static java.util.List<awsservices.proxies.CognitoCredentials> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<awsservices.proxies.CognitoCredentials> result = new java.util.ArrayList<awsservices.proxies.CognitoCredentials>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//AWSServices.CognitoCredentials" + xpathConstraint))
			result.add(awsservices.proxies.CognitoCredentials.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AccessKey
	 */
	public final java.lang.String getAccessKey()
	{
		return getAccessKey(getContext());
	}

	/**
	 * @param context
	 * @return value of AccessKey
	 */
	public final java.lang.String getAccessKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccessKey.toString());
	}

	/**
	 * Set value of AccessKey
	 * @param accesskey
	 */
	public final void setAccessKey(java.lang.String accesskey)
	{
		setAccessKey(getContext(), accesskey);
	}

	/**
	 * Set value of AccessKey
	 * @param context
	 * @param accesskey
	 */
	public final void setAccessKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accesskey)
	{
		getMendixObject().setValue(context, MemberNames.AccessKey.toString(), accesskey);
	}

	/**
	 * @return value of SecretKey
	 */
	public final java.lang.String getSecretKey()
	{
		return getSecretKey(getContext());
	}

	/**
	 * @param context
	 * @return value of SecretKey
	 */
	public final java.lang.String getSecretKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecretKey.toString());
	}

	/**
	 * Set value of SecretKey
	 * @param secretkey
	 */
	public final void setSecretKey(java.lang.String secretkey)
	{
		setSecretKey(getContext(), secretkey);
	}

	/**
	 * Set value of SecretKey
	 * @param context
	 * @param secretkey
	 */
	public final void setSecretKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secretkey)
	{
		getMendixObject().setValue(context, MemberNames.SecretKey.toString(), secretkey);
	}

	/**
	 * @return value of Username
	 */
	public final java.lang.String getUsername()
	{
		return getUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of Username
	 */
	public final java.lang.String getUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Username.toString());
	}

	/**
	 * Set value of Username
	 * @param username
	 */
	public final void setUsername(java.lang.String username)
	{
		setUsername(getContext(), username);
	}

	/**
	 * Set value of Username
	 * @param context
	 * @param username
	 */
	public final void setUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.Username.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of IdentityPoolId
	 */
	public final java.lang.String getIdentityPoolId()
	{
		return getIdentityPoolId(getContext());
	}

	/**
	 * @param context
	 * @return value of IdentityPoolId
	 */
	public final java.lang.String getIdentityPoolId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IdentityPoolId.toString());
	}

	/**
	 * Set value of IdentityPoolId
	 * @param identitypoolid
	 */
	public final void setIdentityPoolId(java.lang.String identitypoolid)
	{
		setIdentityPoolId(getContext(), identitypoolid);
	}

	/**
	 * Set value of IdentityPoolId
	 * @param context
	 * @param identitypoolid
	 */
	public final void setIdentityPoolId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identitypoolid)
	{
		getMendixObject().setValue(context, MemberNames.IdentityPoolId.toString(), identitypoolid);
	}

	/**
	 * @return value of Credentials_CognitoCredentials
	 */
	public final awsservices.proxies.Credentials getCredentials_CognitoCredentials() throws com.mendix.core.CoreException
	{
		return getCredentials_CognitoCredentials(getContext());
	}

	/**
	 * @param context
	 * @return value of Credentials_CognitoCredentials
	 */
	public final awsservices.proxies.Credentials getCredentials_CognitoCredentials(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsservices.proxies.Credentials result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Credentials_CognitoCredentials.toString());
		if (identifier != null)
			result = awsservices.proxies.Credentials.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Credentials_CognitoCredentials
	 * @param credentials_cognitocredentials
	 */
	public final void setCredentials_CognitoCredentials(awsservices.proxies.Credentials credentials_cognitocredentials)
	{
		setCredentials_CognitoCredentials(getContext(), credentials_cognitocredentials);
	}

	/**
	 * Set value of Credentials_CognitoCredentials
	 * @param context
	 * @param credentials_cognitocredentials
	 */
	public final void setCredentials_CognitoCredentials(com.mendix.systemwideinterfaces.core.IContext context, awsservices.proxies.Credentials credentials_cognitocredentials)
	{
		if (credentials_cognitocredentials == null)
			getMendixObject().setValue(context, MemberNames.Credentials_CognitoCredentials.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Credentials_CognitoCredentials.toString(), credentials_cognitocredentials.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cognitoCredentialsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsservices.proxies.CognitoCredentials that = (awsservices.proxies.CognitoCredentials) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AWSServices.CognitoCredentials";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
