// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsservices.proxies;

public class SendMessageRequest
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sendMessageRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSServices.SendMessageRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		QueueUrl("QueueUrl"),
		Body("Body"),
		SendMessageRequest_Credentials("AWSServices.SendMessageRequest_Credentials");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SendMessageRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AWSServices.SendMessageRequest"));
	}

	protected SendMessageRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sendMessageRequestMendixObject)
	{
		if (sendMessageRequestMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AWSServices.SendMessageRequest", sendMessageRequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AWSServices.SendMessageRequest");

		this.sendMessageRequestMendixObject = sendMessageRequestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SendMessageRequest.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static awsservices.proxies.SendMessageRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return awsservices.proxies.SendMessageRequest.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static awsservices.proxies.SendMessageRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsservices.proxies.SendMessageRequest(context, mendixObject);
	}

	public static awsservices.proxies.SendMessageRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsservices.proxies.SendMessageRequest.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of QueueUrl
	 */
	public final java.lang.String getQueueUrl()
	{
		return getQueueUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of QueueUrl
	 */
	public final java.lang.String getQueueUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QueueUrl.toString());
	}

	/**
	 * Set value of QueueUrl
	 * @param queueurl
	 */
	public final void setQueueUrl(java.lang.String queueurl)
	{
		setQueueUrl(getContext(), queueurl);
	}

	/**
	 * Set value of QueueUrl
	 * @param context
	 * @param queueurl
	 */
	public final void setQueueUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String queueurl)
	{
		getMendixObject().setValue(context, MemberNames.QueueUrl.toString(), queueurl);
	}

	/**
	 * @return value of Body
	 */
	public final java.lang.String getBody()
	{
		return getBody(getContext());
	}

	/**
	 * @param context
	 * @return value of Body
	 */
	public final java.lang.String getBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Body.toString());
	}

	/**
	 * Set value of Body
	 * @param body
	 */
	public final void setBody(java.lang.String body)
	{
		setBody(getContext(), body);
	}

	/**
	 * Set value of Body
	 * @param context
	 * @param body
	 */
	public final void setBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String body)
	{
		getMendixObject().setValue(context, MemberNames.Body.toString(), body);
	}

	/**
	 * @return value of SendMessageRequest_Credentials
	 */
	public final awsservices.proxies.Credentials getSendMessageRequest_Credentials() throws com.mendix.core.CoreException
	{
		return getSendMessageRequest_Credentials(getContext());
	}

	/**
	 * @param context
	 * @return value of SendMessageRequest_Credentials
	 */
	public final awsservices.proxies.Credentials getSendMessageRequest_Credentials(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsservices.proxies.Credentials result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SendMessageRequest_Credentials.toString());
		if (identifier != null)
			result = awsservices.proxies.Credentials.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SendMessageRequest_Credentials
	 * @param sendmessagerequest_credentials
	 */
	public final void setSendMessageRequest_Credentials(awsservices.proxies.Credentials sendmessagerequest_credentials)
	{
		setSendMessageRequest_Credentials(getContext(), sendmessagerequest_credentials);
	}

	/**
	 * Set value of SendMessageRequest_Credentials
	 * @param context
	 * @param sendmessagerequest_credentials
	 */
	public final void setSendMessageRequest_Credentials(com.mendix.systemwideinterfaces.core.IContext context, awsservices.proxies.Credentials sendmessagerequest_credentials)
	{
		if (sendmessagerequest_credentials == null)
			getMendixObject().setValue(context, MemberNames.SendMessageRequest_Credentials.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SendMessageRequest_Credentials.toString(), sendmessagerequest_credentials.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sendMessageRequestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsservices.proxies.SendMessageRequest that = (awsservices.proxies.SendMessageRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AWSServices.SendMessageRequest";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
