// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package awsservices.proxies;

public class Topic
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject topicMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AWSServices.Topic";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Arn("Arn"),
		Name("Name"),
		Topic_Credentials("AWSServices.Topic_Credentials");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Topic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AWSServices.Topic"));
	}

	protected Topic(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject topicMendixObject)
	{
		if (topicMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AWSServices.Topic", topicMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AWSServices.Topic");

		this.topicMendixObject = topicMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Topic.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static awsservices.proxies.Topic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return awsservices.proxies.Topic.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static awsservices.proxies.Topic initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new awsservices.proxies.Topic(context, mendixObject);
	}

	public static awsservices.proxies.Topic load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return awsservices.proxies.Topic.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Arn
	 */
	public final java.lang.String getArn()
	{
		return getArn(getContext());
	}

	/**
	 * @param context
	 * @return value of Arn
	 */
	public final java.lang.String getArn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Arn.toString());
	}

	/**
	 * Set value of Arn
	 * @param arn
	 */
	public final void setArn(java.lang.String arn)
	{
		setArn(getContext(), arn);
	}

	/**
	 * Set value of Arn
	 * @param context
	 * @param arn
	 */
	public final void setArn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String arn)
	{
		getMendixObject().setValue(context, MemberNames.Arn.toString(), arn);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Topic_Credentials
	 */
	public final awsservices.proxies.Credentials getTopic_Credentials() throws com.mendix.core.CoreException
	{
		return getTopic_Credentials(getContext());
	}

	/**
	 * @param context
	 * @return value of Topic_Credentials
	 */
	public final awsservices.proxies.Credentials getTopic_Credentials(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		awsservices.proxies.Credentials result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Topic_Credentials.toString());
		if (identifier != null)
			result = awsservices.proxies.Credentials.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Topic_Credentials
	 * @param topic_credentials
	 */
	public final void setTopic_Credentials(awsservices.proxies.Credentials topic_credentials)
	{
		setTopic_Credentials(getContext(), topic_credentials);
	}

	/**
	 * Set value of Topic_Credentials
	 * @param context
	 * @param topic_credentials
	 */
	public final void setTopic_Credentials(com.mendix.systemwideinterfaces.core.IContext context, awsservices.proxies.Credentials topic_credentials)
	{
		if (topic_credentials == null)
			getMendixObject().setValue(context, MemberNames.Topic_Credentials.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Topic_Credentials.toString(), topic_credentials.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return topicMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final awsservices.proxies.Topic that = (awsservices.proxies.Topic) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AWSServices.Topic";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
