// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awsservices.actions;

import awsservices.impl.AWSClients;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import software.amazon.awssdk.services.sns.SnsClient;
import software.amazon.awssdk.services.sns.model.PublishRequest;
import software.amazon.awssdk.services.sns.model.PublishResponse;

public class SNS_Publish extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __credentials;
	private awsservices.proxies.Credentials credentials;
	private java.lang.String subject;
	private java.lang.String body;
	private java.lang.String topic;

	public SNS_Publish(IContext context, IMendixObject credentials, java.lang.String subject, java.lang.String body, java.lang.String topic)
	{
		super(context);
		this.__credentials = credentials;
		this.subject = subject;
		this.body = body;
		this.topic = topic;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.credentials = __credentials == null ? null : awsservices.proxies.Credentials.initialize(getContext(), __credentials);

		// BEGIN USER CODE
		final SnsClient client = AWSClients.getSnsClient(context(), credentials);

		final PublishRequest request = PublishRequest.builder()
				.message(body)
				.subject(subject)
				.topicArn(topic)
				.build();

		final PublishResponse response = client.publish(request);

		return response.messageId();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SNS_Publish";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
